In [1]:
#np.sort : return a sorted copy of an array and also give numpy sorted array
import numpy as np
a = np.random.randint(1,100,15)
a

array([33, 69, 42, 52, 18, 26, 17, 74,  1, 15, 88, 51, 30, 94, 40])

In [4]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[55, 89,  3, 87],
       [35, 51, 91, 45],
       [30, 67, 38, 90],
       [43, 75, 15, 74],
       [84, 80, 35, 66],
       [62, 13, 49, 94]])

In [9]:
np.sort(a)

array([ 1, 15, 17, 18, 26, 30, 33, 40, 42, 51, 52, 69, 74, 88, 94])

In [10]:
np.sort(b)  #default row sorting#

array([[ 3, 55, 87, 89],
       [35, 45, 51, 91],
       [30, 38, 67, 90],
       [15, 43, 74, 75],
       [35, 66, 80, 84],
       [13, 49, 62, 94]])

In [8]:
np.sort(b,axis = 0)

array([[30, 13,  3, 45],
       [35, 51, 15, 66],
       [43, 67, 35, 74],
       [55, 75, 38, 87],
       [62, 80, 49, 90],
       [84, 89, 91, 94]])

In [11]:
#To sort it in descending order
np.sort(a)[::-1]

array([94, 88, 74, 69, 52, 51, 42, 40, 33, 30, 26, 18, 17, 15,  1])

In [12]:
np.sort(b,axis = 0)[::-1]

array([[84, 89, 91, 94],
       [62, 80, 49, 90],
       [55, 75, 38, 87],
       [43, 67, 35, 74],
       [35, 51, 15, 66],
       [30, 13,  3, 45]])

In [13]:
#np.append() : The numpy append() appends values along the mentioned axis at the end of the array.

In [14]:
a

array([33, 69, 42, 52, 18, 26, 17, 74,  1, 15, 88, 51, 30, 94, 40])

In [15]:
np.append(a,666)

array([ 33,  69,  42,  52,  18,  26,  17,  74,   1,  15,  88,  51,  30,
        94,  40, 666])

In [16]:
b

array([[55, 89,  3, 87],
       [35, 51, 91, 45],
       [30, 67, 38, 90],
       [43, 75, 15, 74],
       [84, 80, 35, 66],
       [62, 13, 49, 94]])

In [32]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[55., 89.,  3., 87.,  1.],
       [35., 51., 91., 45.,  1.],
       [30., 67., 38., 90.,  1.],
       [43., 75., 15., 74.,  1.],
       [84., 80., 35., 66.,  1.],
       [62., 13., 49., 94.,  1.]])

In [20]:
#np.concatenate: numpy.concatenate() function concatenate a sequence of arrays along a existing axis.

In [22]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)
print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [23]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [24]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [28]:
np.hstack((c,d))

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [29]:
np.vstack((c,d))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [33]:
#np.unique(): with the help of np.unique() method we can get the unique values from an array given as parameter in np.unique() method.


In [34]:
e = np.array([1,1,1,2,2,2,3,3,3,4,4,5,5,6,6])
np.unique(e)

array([1, 2, 3, 4, 5, 6])

In [35]:
#np.expand_dims: with the help of numpy.expand_dims() method, we can get the expanded dimensions of an array.


In [36]:
a

array([33, 69, 42, 52, 18, 26, 17, 74,  1, 15, 88, 51, 30, 94, 40])

In [39]:
np.shape(a)

(15,)

In [41]:
np.expand_dims(a,axis=0)  #converted into 2d array


array([[33, 69, 42, 52, 18, 26, 17, 74,  1, 15, 88, 51, 30, 94, 40]])

In [42]:
np.expand_dims(a,axis=1)

array([[33],
       [69],
       [42],
       [52],
       [18],
       [26],
       [17],
       [74],
       [ 1],
       [15],
       [88],
       [51],
       [30],
       [94],
       [40]])

In [54]:
#np.where() : The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

In [57]:
a = np.arange(20,40)

In [58]:
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39])

In [59]:
np.where(a > 30, 0,a)

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30,  0,  0,  0,  0,  0,  0,
        0,  0,  0])

In [60]:
np.where(a%2==0,0,a)

array([ 0, 21,  0, 23,  0, 25,  0, 27,  0, 29,  0, 31,  0, 33,  0, 35,  0,
       37,  0, 39])

In [61]:
#np.argmax(): The numpy.argmax() function returns indices of the max element of the array in a particular axis.

In [62]:
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39])

In [63]:
np.argmax(a)   #to find the index of largest element in given array

19

In [64]:
b

array([[55, 89,  3, 87],
       [35, 51, 91, 45],
       [30, 67, 38, 90],
       [43, 75, 15, 74],
       [84, 80, 35, 66],
       [62, 13, 49, 94]])

In [66]:
np.argmax(b,axis=0)  #column

array([4, 0, 1, 5], dtype=int64)

In [67]:
np.argmax(b, axis=1)    #row

array([1, 2, 3, 1, 0, 3], dtype=int64)

In [68]:
np.argmax(b)

23

In [69]:
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39])

In [71]:
np.argmin(a)  #top find the index of minimun element from given array

0

In [72]:
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39])

In [73]:
np.cumsum(a)

array([ 20,  41,  63,  86, 110, 135, 161, 188, 216, 245, 275, 306, 338,
       371, 405, 440, 476, 513, 551, 590])

In [74]:
b

array([[55, 89,  3, 87],
       [35, 51, 91, 45],
       [30, 67, 38, 90],
       [43, 75, 15, 74],
       [84, 80, 35, 66],
       [62, 13, 49, 94]])

In [75]:
np.cumsum(b)

array([  55,  144,  147,  234,  269,  320,  411,  456,  486,  553,  591,
        681,  724,  799,  814,  888,  972, 1052, 1087, 1153, 1215, 1228,
       1277, 1371])

In [76]:
np.cumsum(b , axis=0)

array([[ 55,  89,   3,  87],
       [ 90, 140,  94, 132],
       [120, 207, 132, 222],
       [163, 282, 147, 296],
       [247, 362, 182, 362],
       [309, 375, 231, 456]])

In [77]:
np.cumsum(b, axis=1)

array([[ 55, 144, 147, 234],
       [ 35,  86, 177, 222],
       [ 30,  97, 135, 225],
       [ 43, 118, 133, 207],
       [ 84, 164, 199, 265],
       [ 62,  75, 124, 218]])

In [78]:
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39])

In [79]:
np.cumprod(a)   #cumprod() is same as cumsum but to find product

array([         20,         420,        9240,      212520,     5100480,
         127512000,  -979655296,  -680889216, -1885028864,  1168737792,
         702395392,   299420672,   991526912, -1639350272,    96665600,
        -911671296,  1539571712,  1129578496,   -25690112, -1001914368])

In [80]:
#np.percentile(): this function is used to compute the nth percentile of the given data along the specified axis.

In [81]:
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39])

In [82]:
np.percentile(a,100)

39.0

In [84]:
np.percentile(a,50)

29.5

In [86]:
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39])

In [87]:
np.histogram(a,bins=[0,10,20,30,40])

(array([ 0,  0, 10, 10], dtype=int64), array([ 0, 10, 20, 30, 40]))

In [3]:
import numpy as np
salary = np.array([40000,4500000,60000,80000])
experience = np.array([1,2,4,6])
np.corrcoef(salary,experience)

array([[ 1.        , -0.36904144],
       [-0.36904144,  1.        ]])

In [4]:
a = np.random.randint(10,30,10)

In [5]:
a

array([24, 17, 24, 24, 13, 23, 15, 15, 26, 20])

In [6]:
items = [5,10,13,20,26]

In [7]:
np.isin(a,items)

array([False, False, False, False,  True, False, False, False,  True,
        True])

In [8]:
a[np.isin(a,items)]

array([13, 26, 20])

In [9]:
a

array([24, 17, 24, 24, 13, 23, 15, 15, 26, 20])

In [11]:
np.flip(a)

array([20, 26, 15, 15, 23, 13, 24, 24, 17, 24])

In [12]:
b = np.arange(12).reshape(3,4)

In [13]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [16]:
np.flip(b,axis = 1)

array([[ 3,  2,  1,  0],
       [ 7,  6,  5,  4],
       [11, 10,  9,  8]])

In [20]:
a.dtype

dtype('int32')

In [21]:
a

array([24, 17, 24, 24, 13, 23, 15, 15, 26, 20])

In [24]:
np.put(a,[2,3],[48,50])  #this function makes permanent change in given array

In [25]:
a

array([24, 17, 48, 50, 13, 23, 15, 15, 26, 20])

In [26]:
#np.delete() : it is used to delete the items from array
np.delete(a,2)  #(array,index)

array([24, 17, 50, 13, 23, 15, 15, 26, 20])

In [27]:
np.delete(a,[0,3])  #its temporary

array([17, 48, 13, 23, 15, 15, 26, 20])

In [28]:
a = np.array([1,2,3,4,5])
b = np.array([3,4,5,6,7])
np.union1d(a,b)

array([1, 2, 3, 4, 5, 6, 7])

In [29]:
np.intersect1d(a,b)

array([3, 4, 5])

In [30]:
np.setdiff1d(a,b)

array([1, 2])

In [32]:
np.setxor1d(a,b)

array([1, 2, 6, 7])

In [33]:
np.in1d(a,2)

array([False,  True, False, False, False])

In [34]:
a


array([1, 2, 3, 4, 5])

In [38]:
b = np.array([20,30,45,80,13,78,19])

In [39]:
np.clip(b, a_min = 20 , a_max =75)

array([20, 30, 45, 75, 20, 75, 20])