In [6]:
import numpy as np 
a = np.array([2,3,4])
print(a)
print(type(a))


[2 3 4]
<class 'numpy.ndarray'>


In [7]:
b = np.array([[1,3,5],[2,4,6]])
print(b)

[[1 3 5]
 [2 4 6]]


In [9]:
c =  np.array([[1,2],[3,4],[4,5],[7,8]])
print(c)

[[1 2]
 [3 4]
 [4 5]
 [7 8]]


In [18]:
 a = np.array([1,2,3],dtype= float)
 b = np.array([1,0,3],dtype= bool)
 c = np.array([1,0,1], dtype = complex)
print(a)
print(b)
print(c)

[1. 2. 3.]
[ True False  True]
[1.+0.j 0.+0.j 1.+0.j]


In [2]:
import numpy as np

In [3]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [9]:
# with reshape means can be converted into rows and column and in matrix form
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
#np.ones and np.zeros used in initialization of array
a = np.ones((4,4))
b = np.zeros((3,3))
c = np.random.random((3,3))
print(a)
print(b)
print(c)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0.99188444 0.6809485  0.33805622]
 [0.32154276 0.56954177 0.03632574]
 [0.9761524  0.63433684 0.83177664]]


In [16]:
# np.linspace means linear space like it generate numbers with same space where its syntax is (lower range, upper range, total no of required items between that range)
np.linspace(-5,5,5)
            

array([-5. , -2.5,  0. ,  2.5,  5. ])

In [119]:
# np.identity is used to create identity matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
#Array attribute


In [35]:
a1 = np.arange(10)
a2 = np.arange(12,dtype = float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [117]:
#ndim means number of dimensions:
np.ndim(a3)


3

In [120]:
# shape tells no of rows and column
print(a2.shape)
a3

(3, 4)


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [121]:
#size tells no of items
a3.size

27

In [44]:
#items size tells how much space is occupied in memory
a3.itemsize

4

In [45]:
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int32


In [50]:
# changing datatype astype
a3.astype(np.int64)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int64)

In [53]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
print(a1)
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [56]:
#scalar operations means doing operations in single numpy array
a1*2  #+,-,**,/,%, all can be performed#

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [57]:
# relational operators or comparison operator
a1>5

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [58]:
#vector operations can be performed with two or more numpy arrays of same size
a1+a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [1]:
import numpy as np

In [3]:
a1 = np.random.random((3,3))
a1 = np.round(a1*50)
a1

array([[22., 22., 24.],
       [17., 12., 24.],
       [34., 39., 31.]])

In [8]:
#max/min/sum/product
a = np.max(a1)
b = np.min(a1)
c = np.sum(a1)
d = np.prod(a1)
print(a)
print(b)
print(c)
print(d)


39.0
12.0
225.0
2337777801216.0


In [9]:
#to find its item from each row and column 
#0-> column and 1 ->row
np.max(a1,axis = 1)

array([24., 24., 39.])

In [11]:
np.min(a1,axis=0)

array([17., 12., 24.])

In [12]:
#statistical related functions:
#mean/median/std/var
np.mean(a1)

25.0

In [13]:
#to find its mean row wise or column wise we have:
np.mean(a1,axis = 1)

array([22.66666667, 17.66666667, 34.66666667])

In [14]:
np.median(a1)

24.0

In [15]:
np.std(a1)

7.930251502246879

In [16]:
np.var(a1)

62.888888888888886

In [17]:
#trignometric functions:
np.cos(a1)

array([[-0.99996083, -0.99996083,  0.42417901],
       [-0.27516334,  0.84385396,  0.42417901],
       [-0.84857027,  0.26664293,  0.91474236]])

In [19]:
#dot product is applicable when column of first matrix is equal to row of second matrix
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [21]:
#log and exponents
np.log(a1)

array([[3.09104245, 3.09104245, 3.17805383],
       [2.83321334, 2.48490665, 3.17805383],
       [3.52636052, 3.66356165, 3.4339872 ]])

In [22]:
np.exp(a1)

array([[3.58491285e+09, 3.58491285e+09, 2.64891221e+10],
       [2.41549528e+07, 1.62754791e+05, 2.64891221e+10],
       [5.83461743e+14, 8.65934004e+16, 2.90488497e+13]])

In [28]:
#round/floor/cell 
#round function round of the value to the nearest integer
np.round(np.random.random((3,3))*100)

array([[21., 76., 69.],
       [71., 43., 82.],
       [78., 19., 59.]])

In [31]:
#floor function takes bacward like if 6.9 than floor function makes it 6
np.floor(np.random.random((3))*100)

array([38., 96., 69.])

In [35]:
#ceil function takes forward like if we have 6.1 than using cell function it will be 7
np.ceil(np.random.random((3,3))*50)

array([[ 8., 27., 32.],
       [12.,  2., 32.],
       [ 8., 10., 34.]])

In [39]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
a1[4]

4

In [45]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [48]:
a2[2,2]  # where 2 is row and 2 is column

10

In [49]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [50]:
a3[1,0,1]  #where first item is which 2d matrix and second item is its row and thirf items is its column

5

In [53]:
a3[1,1,0]

6

In [56]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
a1[2:5]

array([2, 3, 4])

In [58]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [59]:
a2[0,:]

array([0, 1, 2, 3])

In [61]:
a2[1,:]

array([4, 5, 6, 7])

In [65]:
a2[:,3]

array([ 3,  7, 11])

In [66]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [68]:
a2[0:2,0:2]

array([[0, 1],
       [4, 5]])

In [69]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [70]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [71]:
a2[0:2,1:3]

array([[1, 2],
       [5, 6]])

In [77]:
a2[1,::3]

array([4, 7])

In [80]:
a2[:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [83]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [84]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [85]:
a3[0:3:2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [86]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [89]:
a3[0,1:2]

array([[3, 4, 5]])

In [90]:
a3[1,:,1:2]

array([[10],
       [13],
       [16]])

In [94]:
a3[0:3:2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [95]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [96]:
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [97]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [98]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [99]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [100]:
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [102]:
for i in np.nditer(a3): #to print all the items in 2d or 3d nd.iter() function is used
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [104]:
#transpose
np.transpose(a2)  #both are same
a2.T


array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [106]:
# ravel convert other dimensions array into 1d 
np.ravel(a2)
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [107]:
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [122]:
#horizontal stacking
a4 =  np.arange(12).reshape(3,4)
a5 =  np.arange(12,24).reshape(3,4)
np.hstack((a4,a5))


array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [111]:
#vertival stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [112]:
#splitting hsplit means we distinguish it vertically and vsplit means we split it horizontally it is oppsite of stack
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [113]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [116]:
np.vsplit(a4,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]